### ISSUE TITLE
libFilters 3.3 - Retrait station update not working automatically via libfilters register filter

### ISSUE THREAD

**Issue by Baertram** [Randactyl/LibFilters-2.0#5]
Hey Randactyl, I've just tested to implement the retrait station into my addons and the filter functions are not called via HandleDirtyEvent all the time as it seems.
Example: If I register a filter I can see it within libFilters but the inventory at the retrait station is not updated.

If I close or open the retrait station the update takles place. But not in between if I register or unregister a new filter.

I've tested this with debug messages and ZGOO. The debug messages in your helper function for the retrait panel are only shown if I open or close the retrait station, or if I change from weapons to armor or back inside the retrait station.

**Comment by Baertram** [comment]
I've tried to change the udater function to

RETRAIT = function()
        ZO_RETRAIT_STATION_KEYBOARD.retraitPanel.inventory:HandleDirtyEvent()
    end,

but this didn't help. Seems as if the HandleDirtyEvent function is not calling ZO_RetraitStation_CanItemBeRetraited all the time.

**Comment by Randactyl** [comment]
Are you calling `LibFilters:RequestUpdate(LF_RETRAIT)`?

I tested with the test file included with the standalone lib. Uncomment the file in the manifest, open station, type `/testfilters`, list gets filtered, use the command again, list is back.

Also, for the future you can comment on an issue even if it is closed. Could've reopened the existing retrait research item :)

**Comment by Baertram** [comment]
aaaah mea culpa! The retrait station behaves different then others and thus I had forgotten to implement the LibFilters:RequestUpdate(LF_RETRAIT) call in my filter button function! 
Thanks for the hint.

About the new issue: I'm not used to github and haven't seen the "Closed" button before :-)

**Comment by Randactyl** [comment]
oh no worries, yeah I'm still learning it too.
